security:
  # Configuración para aceptar contraseñas en texto plano
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'plaintext'

  # Proveedor de usuarios en memoria
  providers:
    app_user_provider:
      memory:
        users:
          '%env(LOGIN_USERNAME)%':
            password: '%env(LOGIN_PASSWORD)%'
            roles: ['ROLE_ADMIN']

  # Firewalls
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider

      # Login
      form_login:
        login_path: login
        check_path: login
        default_target_path: inicio

      # Logout
      logout:
        path: logout
        target: login

  # Control de acceso
  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: ROLE_ADMIN }